from_latest_tag = true
ignore_merge_commits = true
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "Gérald Lelong", username = "lelongg" },
  { signature = "RobWalt", username = "RobWalt" }
]

[bump_profiles]

[packages]
